### ISSUE TITLE
FAILED TO UNPACK ATOM trees2

### ISSUE THREAD

**Issue by M8BWNN** [zack-bitcoin/amoveo-mining-pool#13]
Hi,

i just installed amoveo full node ( port 8081, synced ) and connected this mining pool ( changed only pubkey in apps/amoveo_mining_pool/src/config.erl  ). Mining Pool is starting, but just printing "Progess / Error reports" and not accepting miners on 8085 ( by the way: is this pool getwork or stratum or both? i use this software: https://github.com/zack-bitcoin/VeoCL )

Exec: /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool/erts-7.3/bin/erlexec -noshell -noinput +Bd -boot /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool/releases/0.1.0/amoveo_mining_pool -mode embedded -boot_var ERTS_LIB_DIR /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool/lib -config /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool/releases/0.1.0/sys.config -args_file /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool/releases/0.1.0/vm.args -pa -- foreground
Root: /home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool
/home/docki/amoveo/amoveo-mining-pool/_build/prod/rel/amoveo_mining_pool

=PROGRESS REPORT==== 8-Mar-2019::17:41:20 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.557.0>},
                       {id,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:20 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.558.0>},
                       {id,overload},
                       {mfargs,{overload,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:20 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.556.0>},
                       {id,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:20 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.559.0>},
                       {id,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:20 ===
         application: sasl
          started_at: amoveo_mining_pool@c37a3952bd22
FAILED TO UNPACK ATOM trees2
died!
=ERROR REPORT==== 8-Mar-2019::17:41:22 ===
** Generic server rewards_pusher terminating 
** Last message in was {'$gen_cast',new_height}
** When Server state == []
** Reason for termination == 
** {{badmatch,2},
    [{packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,29}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {rewards_pusher,new_height_internal,0,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,26}]},
     {rewards_pusher,handle_cast,2,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,12}]}]}

=CRASH REPORT==== 8-Mar-2019::17:41:22 ===
  crasher:
    initial call: rewards_pusher:init/1
    pid: <0.550.0>
    registered_name: rewards_pusher
    exception exit: {{badmatch,2},
                     [{packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,29}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,31}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,31}]},
                      {rewards_pusher,new_height_internal,0,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                           {line,26}]},
                      {rewards_pusher,handle_cast,2,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                           {line,12}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 826)
    ancestors: [amoveo_mining_pool_sup,<0.436.0>]
    messages: []
    links: [<0.542.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 318187
    stack_size: 27
    reductions: 245179
  neighbours:

=SUPERVISOR REPORT==== 8-Mar-2019::17:41:22 ===
     Supervisor: {local,amoveo_mining_pool_sup}
     Context:    child_terminated
     Reason:     {{badmatch,2},
                  [{packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,29}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,31}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,31}]},
                   {rewards_pusher,new_height_internal,0,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                        {line,26}]},
                   {rewards_pusher,handle_cast,2,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                        {line,12}]}]}
     Offender:   [{pid,<0.550.0>},
                  {id,rewards_pusher},
                  {mfargs,{rewards_pusher,start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:22 ===
          supervisor: {local,amoveo_mining_pool_sup}
             started: [{pid,<0.565.0>},
                       {id,rewards_pusher},
                       {mfargs,{rewards_pusher,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]
FAILED TO UNPACK ATOM trees2
died!
=ERROR REPORT==== 8-Mar-2019::17:41:24 ===
** Generic server rewards_pusher terminating 
** Last message in was {'$gen_cast',new_height}
** When Server state == []
** Reason for termination == 
** {{badmatch,2},
    [{packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,29}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {rewards_pusher,new_height_internal,0,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,26}]},
     {rewards_pusher,handle_cast,2,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,12}]}]}

=CRASH REPORT==== 8-Mar-2019::17:41:24 ===
  crasher:
    initial call: rewards_pusher:init/1
    pid: <0.565.0>
    registered_name: rewards_pusher
    exception exit: {{badmatch,2},
                     [{packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,29}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,31}]},
                      {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                      {packer,unpack_helper,1,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                           {line,31}]},
                      {rewards_pusher,new_height_internal,0,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                           {line,26}]},
                      {rewards_pusher,handle_cast,2,
                          [{file,
                               "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                           {line,12}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 826)
    ancestors: [amoveo_mining_pool_sup,<0.436.0>]
    messages: []
    links: [<0.542.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 318187
    stack_size: 27
    reductions: 245179
  neighbours:

=SUPERVISOR REPORT==== 8-Mar-2019::17:41:24 ===
     Supervisor: {local,amoveo_mining_pool_sup}
     Context:    child_terminated
     Reason:     {{badmatch,2},
                  [{packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,29}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,31}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                   {packer,unpack_helper,1,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
                        {line,31}]},
                   {rewards_pusher,new_height_internal,0,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                        {line,26}]},
                   {rewards_pusher,handle_cast,2,
                       [{file,
                            "/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                        {line,12}]}]}
     Offender:   [{pid,<0.565.0>},
                  {id,rewards_pusher},
                  {mfargs,{rewards_pusher,start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]

=PROGRESS REPORT==== 8-Mar-2019::17:41:24 ===
          supervisor: {local,amoveo_mining_pool_sup}
             started: [{pid,<0.567.0>},
                       {id,rewards_pusher},
                       {mfargs,{rewards_pusher,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]
FAILED TO UNPACK ATOM trees2
died!
=ERROR REPORT==== 8-Mar-2019::17:41:26 ===
** Generic server rewards_pusher terminating 
** Last message in was {'$gen_cast',new_height}
** When Server state == []
** Reason for termination == 
** {{badmatch,2},
    [{packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,29}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
     {packer,unpack_helper,1,
             [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/default/lib/encrypter/src/packer.erl"},
              {line,31}]},
     {rewards_pusher,new_height_internal,0,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,26}]},
     {rewards_pusher,handle_cast,2,
                     [{file,"/home/docki/amoveo/amoveo-mining-pool/_build/prod/lib/amoveo_mining_pool/src/rewards_pusher.erl"},
                      {line,12}]}]}

**Comment by zack-bitcoin** [comment]
turn them off.
use `./rebar3 upgrade` in each repository to update the dependencies.
use `git pull` in each repository to get the latest version of the code. 
When you turn them back on, the problem should be fixed.
