### ISSUE TITLE
Pool Crash and Attach.sh fails to connect to server

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo-mining-pool#2]
The mining pool crashed on me and trying to start it up gave another crash dump. I'll try to stand the pool up from scratch next, which will likely work. Just wanted to capture and report this while I saw it.

![image](https://user-images.githubusercontent.com/35471470/35187907-f8b62dd6-fdf1-11e7-9d61-e8dd8ea40bbc.png)

![image](https://user-images.githubusercontent.com/35471470/35187909-05b3c818-fdf2-11e7-8fab-94503cdc34de.png)

**Comment by Mandelhoff** [comment]
Update - I deleted my mining pool and did a fresh clone and build and attach. Attach told me "Node is not running!".

I gave my node the api:off(). and halt(). Then, I did "make prod-go" and "make prod-attach" on the node. The node appeared ok, but the mining pool still tells me "Node not running!".

I'm not sure what to try next, so suggestions are very welcome.

![image](https://user-images.githubusercontent.com/35471470/35187987-60ad1f84-fdf3-11e7-962a-f8a7401f471f.png)

**Comment by zack-bitcoin** [comment]
Yes, this is a confusing error message.
What I should have said is: "The mining pool is currently turned off. use 'sh start.sh' to turn the mining pool on."

Thank you for this helpful report. I will update the error message so that people will not be confused about this in the future.

**Comment by zack-bitcoin** [comment]
It looks like I was not the one who wrote this error message.
It is a default message generated by rebar3 releases.
I am not sure how to fix this message.
Maybe I will just explain this issue in the README.

**Comment by zack-bitcoin** [comment]
ok, I updated the readme to explain the issue. So I will consider this issue solved for now.

**Comment by Mandelhoff** [comment]
The "sh start.sh" looks successful, but "Node is still not running!" still happens when I call attach.sh.

![image](https://user-images.githubusercontent.com/35471470/35188534-74f2ec36-fdfc-11e7-9bf5-32b5755112f3.png)

**Comment by Mandelhoff** [comment]
I rebooted, started the full node, and then tried to run the mining pool. The attach.sh to the pool gave this crash dump. Left side of screenshot is the full node and right side is the pool start/attach.

Any idea why the pool attach fails or suggestions on what to try?
Thank you.

![image](https://user-images.githubusercontent.com/35471470/35188602-165c7d16-fdfe-11e7-95cf-eb8386e4e0b4.png)

**Comment by zack-bitcoin** [comment]
Thank you for this helpful error report.

The blockchain looks like a minning pool or c-miner is successfully communicating with it.
If you connect a mining pool to a blockchain node, then you should not simultaneously connect a c-miner directly to that same blockchain node. They will mess up each other's work.

If you want to also run a miner, it should be connected to the mining pool.

Which operating system is this? It looks like some kind of Linux. 
I only use the mining pool from a server I am renting, that way it consistently has an externally accessible IP address where miners can contact it. 
The mining pool usually works on my first try when I follow the steps as you have described.

I will try to reproduce the error after I sleep.

**Comment by Mandelhoff** [comment]
Yes, the full node is printing "got this data", but  I have no idea who/what is polling the full node if the mining pool is not running.

I am using linux in Azure:
![image](https://user-images.githubusercontent.com/35471470/35190668-571aabc4-fe2c-11e7-840a-1a941c1a2fde.png)

This is a new VM where I didn't setup a local miner at all. I had a remote miner pointed at the pool, but not any miners pointed at this full node instance. (I deleted the old Azure VM instance where I had a local miner setup too.)

I have port 8085 open on my VM, but not port 8080 or 8081.

**Comment by Mandelhoff** [comment]
Following up with details:
I rebooted a few times, and had no luck recovering my node/pool combination. After a few tries, I deleted my clones of the node and pool and got fresh copies. I stood them up fine, and mining a few blocks worked for me. The pool has been "alive" for ~48 hours, which is about double the duration when it stopped working for this issue.

**Comment by zack-bitcoin** [comment]
I am glad it is working for you now.
Maybe your issue was using an old version of the code.
