### ISSUE TITLE
Pool Errors: "Node not synced" but it is.

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo-mining-pool#5]
My full node got out of sync, so I entirely deleted my node and pool. I cloned fresh copies.

I built, started, and synced my node.
Then, I built and started the pool and got these errors:

![image](https://user-images.githubusercontent.com/35471470/35754145-02429782-0828-11e8-9e51-0dd9a84e7274.png)

![image](https://user-images.githubusercontent.com/35471470/35754156-09c1a34a-0828-11e8-95c5-2124bbb85f73.png)

I tried rebuilding and verified my node block height matched your light wallet's block height value. When I tried again, I got a slightly different error from the pool:

![image](https://user-images.githubusercontent.com/35471470/35754195-2ddfe052-0828-11e8-906a-c9e58a50d12d.png)

**Comment by Mandelhoff** [comment]
Update:
This can probably be low priority. I think I got my pool working after rebooting.

**Comment by zack-bitcoin** [comment]
The mining pool is complaining saying there is no Amoveo running on the system. Very odd.
Thanks for sharing the report.
